#include "app.h"
#include "csv_parser.h"
#include "logger.h"
#include <commctrl.h>
#include <shellapi.h>

int App::Run(int n){ SetProcessDPIAware(); INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_LISTVIEW_CLASSES|ICC_PROGRESS_CLASS}; InitCommonControlsEx(&ic);
WNDCLASSW wc{}; wc.hInstance=h_; wc.lpszClassName=L"VersionDownloaderWnd"; wc.lpfnWndProc=WndProc; wc.hCursor=LoadCursor(nullptr,IDC_ARROW); RegisterClassW(&wc);
hwnd_=CreateWindowExW(0,wc.lpszClassName,L"Version Downloader",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1100,720,nullptr,nullptr,h_,this); ShowWindow(hwnd_,n);
MSG msg; while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);} return (int)msg.wParam; }
LRESULT CALLBACK App::WndProc(HWND h,UINT m,WPARAM w,LPARAM l){ App* a=(App*)GetWindowLongPtrW(h,GWLP_USERDATA); if(m==WM_NCCREATE){a=(App*)((CREATESTRUCTW*)l)->lpCreateParams; SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)a); a->hwnd_=h;} return a?a->Handle(m,w,l):DefWindowProcW(h,m,w,l);} 
LRESULT App::Handle(UINT m,WPARAM w,LPARAM l){ switch(m){ case WM_CREATE: CreateMainUi(hwnd_,h_,ui_); return 0; case WM_SIZE: ResizeMainUi(hwnd_,ui_); return 0; case WM_COMMAND: switch(LOWORD(w)){case 102:LoadFromUrl();break;case 108:LoadFromLocal();break;case 104:StartDownload();break;case 105:Cancel();break;case 109:OpenDownloads();break;case 110:SetWindowTextW(ui_.logEdit,L"");break;} return 0;
case WM_APP_LOG:{auto* s=(std::wstring*)l; AppendLogText(ui_.logEdit,*s); delete s; return 0;} case WM_APP_PROGRESS:{auto* p=(DownloadProgressPayload*)w; SendMessageW(ui_.progress,PBM_SETPOS,p->percent,0); SetStatus(p->row,L"下载中 "+std::to_wstring(p->percent)+L"%"); wchar_t t[128]; wsprintfW(t,L"速度: %.1f KB/s",p->speedKB); SetWindowTextW(ui_.speedText,t); wsprintfW(t,L"大小: %llu / %llu",p->downloaded,p->total); SetWindowTextW(ui_.sizeText,t); delete p; return 0;} case WM_APP_DONE:{auto* d=(DownloadDonePayload*)w; if(d->success) SetStatus(d->row,L"已完成"); else if(d->message==L"已取消") SetStatus(d->row,L"已取消"); else SetStatus(d->row,L"失败"); AppendLogText(ui_.logEdit,BuildLogLine(d->message)); delete d; return 0;} case WM_DESTROY: PostQuitMessage(0); return 0;} return DefWindowProcW(hwnd_,m,w,l);} 
void App::LoadFromUrl(){ wchar_t u[2048]{}; GetWindowTextW(ui_.urlEdit,u,2048); std::wstring t,e; if(!LoadUtf8TextFromHttp(u,t,e)||!ParseCsvText(t,items_)){ AppendLogText(ui_.logEdit,BuildLogLine(L"加载失败: "+e)); return;} Populate(); AppendLogText(ui_.logEdit,BuildLogLine(L"URL加载成功")); }
void App::LoadFromLocal(){ wchar_t p[MAX_PATH]=L""; OPENFILENAMEW o{sizeof(o)}; o.hwndOwner=hwnd_; o.lpstrFile=p; o.nMaxFile=MAX_PATH; o.lpstrFilter=L"CSV\0*.csv\0"; if(!GetOpenFileNameW(&o)) return; std::wstring t; if(!LoadUtf8TextFile(p,t)||!ParseCsvText(t,items_)){AppendLogText(ui_.logEdit,BuildLogLine(L"本地CSV加载失败"));return;} Populate(); AppendLogText(ui_.logEdit,BuildLogLine(L"本地CSV加载成功")); }
void App::Populate(){ ListView_DeleteAllItems(ui_.list); for(size_t i=0;i<items_.size();++i){ LVITEMW it{}; it.mask=LVIF_TEXT; it.iItem=(int)i; std::wstring idx=std::to_wstring(items_[i].index); it.pszText=idx.data(); ListView_InsertItem(ui_.list,&it); ListView_SetItemText(ui_.list,i,1,items_[i].name.data()); ListView_SetItemText(ui_.list,i,2,items_[i].filename.data()); ListView_SetItemText(ui_.list,i,3,items_[i].size.data()); ListView_SetItemText(ui_.list,i,4,items_[i].url.data()); ListView_SetItemText(ui_.list,i,5,items_[i].status.data()); }}
void App::SetStatus(int r,const std::wstring& s){ if(r<0||r>=(int)items_.size()) return; items_[r].status=s; ListView_SetItemText(ui_.list,r,5,(LPWSTR)s.c_str()); }
void App::StartDownload(){ if(worker_.IsRunning()) return; int r=ListView_GetNextItem(ui_.list,-1,LVNI_SELECTED); if(r<0) return; SetStatus(r,L"等待下载"); std::wstring save=downloadDir_+L"\\"+items_[r].filename; worker_.Start(hwnd_,r,items_[r].url,save,WM_APP_PROGRESS,WM_APP_LOG,WM_APP_DONE); }
void App::Cancel(){ worker_.Cancel(); }
void App::OpenDownloads(){ ShellExecuteW(hwnd_,L"open",downloadDir_.c_str(),nullptr,nullptr,SW_SHOW); }
