#include "pch.h"
#include "app.h"
#include "http_directory_scanner.h"
#include "logger.h"
#include "string_utils.h"
#include "version.h"
#include <fstream>
#include <filesystem>

static std::wstring ExeDir(){ wchar_t p[MAX_PATH]{}; GetModuleFileNameW(nullptr,p,MAX_PATH); return std::filesystem::path(p).parent_path().wstring(); }
static std::wstring IniPath(){ return ExeDir()+L"\\config.ini"; }

int App::Run(int n){ SetProcessDPIAware(); INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_LISTVIEW_CLASSES|ICC_PROGRESS_CLASS}; InitCommonControlsEx(&ic);
WNDCLASSW wc{}; wc.hInstance=h_; wc.lpszClassName=L"VersionDownloaderWnd"; wc.lpfnWndProc=WndProc; wc.hCursor=LoadCursor(nullptr,IDC_ARROW); RegisterClassW(&wc);
hwnd_=CreateWindowExW(0,wc.lpszClassName,L"HTTP路径下载工具",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1250,780,nullptr,nullptr,h_,this); ShowWindow(hwnd_,n);
AppendLogText(BuildLogLine(std::wstring(L"启动 ") + APP_NAME + L" v" + APP_VERSION));
AppendLogText(BuildLogLine(std::wstring(L"构建时间: ") + BUILD_DATE));
AppendLogText(BuildLogLine(L"程序初始化完成"));
MSG msg; while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);} return (int)msg.wParam; }
LRESULT CALLBACK App::WndProc(HWND h,UINT m,WPARAM w,LPARAM l){ App* a=(App*)GetWindowLongPtrW(h,GWLP_USERDATA); if(m==WM_NCCREATE){a=(App*)((CREATESTRUCTW*)l)->lpCreateParams; SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)a); a->hwnd_=h;} return a?a->Handle(m,w,l):DefWindowProcW(h,m,w,l);} 
LRESULT App::Handle(UINT m,WPARAM w,LPARAM l){ switch(m){ case WM_CREATE: CreateMainUi(hwnd_,h_,ui_); LoadConfig(); SetWindowTextW(ui_.downloadDirEdit,downloadDir_.c_str()); EnableWindow(ui_.cancelBtn,FALSE); return 0; case WM_SIZE: ResizeMainUi(hwnd_,ui_); return 0;
case WM_NOTIFY: if(((LPNMHDR)l)->hwndFrom==ui_.list){ if(((LPNMHDR)l)->code==NM_DBLCLK){ int r=ListView_GetNextItem(ui_.list,-1,LVNI_SELECTED); if(r>=0) StartDownload(true,r);} if(((LPNMHDR)l)->code==NM_RCLICK){ POINT p; GetCursorPos(&p); TrackPopupMenu(ui_.listMenu,TPM_RIGHTBUTTON,p.x,p.y,0,hwnd_,nullptr);} } return 0;
case WM_CONTEXTMENU: if((HWND)w==ui_.logEdit){ POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)}; TrackPopupMenu(ui_.logMenu,TPM_RIGHTBUTTON,p.x,p.y,0,hwnd_,nullptr); return 0;} break;
case WM_KEYDOWN: if((GetKeyState(VK_CONTROL)&0x8000) && w=='A'){ ListView_SetItemState(ui_.list,-1,LVIS_SELECTED,LVIS_SELECTED); return 0;} break;
case WM_COMMAND: switch(LOWORD(w)){case 102:ScanHttpDirectoryUrl();break;case 104:StartDownload();break;case 113:DownloadAll();break;case 105:Cancel();break;case 109:OpenDownloads();break;case 110:SetWindowTextW(ui_.logEdit,L"");break;case 112:ChooseDownloadDir(); break;case 1201:StartDownload();break;case 1202:CopySelectedUrls();break;case 1203:OpenDownloads();break;case 1204:ClearStatuses();break;case 1301: SendMessageW(ui_.logEdit,WM_COPY,0,0);break;case 1302:SetWindowTextW(ui_.logEdit,L"");break;case 1303:SaveLogs();break;} return 0;
case WM_APP_LOG:{auto* s=(std::wstring*)l; AppendLogText(*s); delete s; return 0;} case WM_APP_PROGRESS:{auto* p=(DownloadProgressPayload*)w; SetStatus(p->row,L"下载中 "+std::to_wstring(p->percent)+L"%"); wchar_t t[256]; wsprintfW(t,L"当前文件: %s (%d/%d)",p->filename.c_str(),p->fileIndex,p->fileCount); SetWindowTextW(ui_.fileText,t); wsprintfW(t,L"速度: %.1f KB/s",p->speedKB); SetWindowTextW(ui_.speedText,t); if(p->total){ wsprintfW(t,L"大小: %llu / %llu",p->downloaded,p->total); SetWindowTextW(ui_.sizeText,t); unsigned long long remain=p->total-p->downloaded; int sec=p->speedKB>0?(int)(remain/(p->speedKB*1024.0)):0; wsprintfW(t,L"预计剩余: %d 秒",sec); SetWindowTextW(ui_.etaText,t);} else {SetWindowTextW(ui_.sizeText,L"大小: 未知"); SetWindowTextW(ui_.etaText,L"预计剩余: 未知");}
            unsigned long long now=sumDone_+p->downloaded; int totalP=sumTotal_? (int)(now*100/sumTotal_):0; SendMessageW(ui_.progress,PBM_SETPOS,totalP,0); delete p; return 0;} case WM_APP_DONE:{auto* d=(DownloadDonePayload*)w; if(d->success) {SetStatus(d->row,L"已完成"); sumDone_ += d->downloaded;} else if(d->message==L"已取消") SetStatus(d->row,L"已取消"); else SetStatus(d->row,L"失败"); AppendLogText(BuildLogLine(d->message)); bool cancelAll=d->cancelledAll || d->message==L"已取消"; delete d; queuePos_++; if(cancelAll || queuePos_>= (int)queue_.size()){ SetUiBusy(false); AppendLogText(BuildLogLine(L"下载任务结束，共处理: "+std::to_wstring(queuePos_)+L" 项")); }
            else { int row=queue_[queuePos_]; SetStatus(row,L"等待"); StartDownload(true,row);} return 0;}
case WM_CLOSE: if(worker_.IsRunning()){ if(MessageBoxW(hwnd_,L"正在下载，是否取消并退出？",L"确认",MB_YESNO|MB_ICONQUESTION)==IDYES){Cancel(); DestroyWindow(hwnd_);} return 0;} break;
case WM_DESTROY: SaveConfig(); PostQuitMessage(0); return 0;} return DefWindowProcW(hwnd_,m,w,l);} 

void App::ScanHttpDirectoryUrl(){ wchar_t u[2048]{}; GetWindowTextW(ui_.urlEdit,u,2048); if(wcslen(u)==0){AppendLogText(BuildLogLine(L"HTTP目录地址为空")); return;} AppendLogText(BuildLogLine(L"开始扫描目录")); std::vector<RemoteFileItem> files; std::wstring e; if(!ScanHttpDirectory(u,files,e)){ AppendLogText(BuildLogLine(L"扫描失败: "+e)); return;} items_.clear(); unsigned long long total=0; int idx=1; for(auto& f:files){ VersionItem v; v.index=idx++; v.name=f.name; v.filename=f.name; v.url=f.url; v.sizeKnown=f.sizeKnown; v.sizeBytes=f.size; v.size=f.sizeKnown?FormatBytes(f.size):L"未知"; v.status=L"可下载"; if(f.sizeKnown) total+=f.size; items_.push_back(std::move(v)); } Populate(); AppendLogText(BuildLogLine(L"发现文件数量: "+std::to_wstring(items_.size()))); AppendLogText(BuildLogLine(L"总大小: "+FormatBytes(total))); }
void App::Populate(){ ListView_DeleteAllItems(ui_.list); for(size_t i=0;i<items_.size();++i){ LVITEMW it{}; it.mask=LVIF_TEXT; it.iItem=(int)i; std::wstring idx=std::to_wstring(items_[i].index); it.pszText=idx.data(); ListView_InsertItem(ui_.list,&it); ListView_SetItemText(ui_.list,i,1,items_[i].filename.data()); ListView_SetItemText(ui_.list,i,2,items_[i].size.data()); ListView_SetItemText(ui_.list,i,3,items_[i].url.data()); ListView_SetItemText(ui_.list,i,4,items_[i].status.data()); }}
void App::SetStatus(int r,const std::wstring& s){ if(r<0||r>=(int)items_.size()) return; items_[r].status=s; ListView_SetItemText(ui_.list,r,4,(LPWSTR)s.c_str()); }
std::vector<int> App::SelectedRows() const{ std::vector<int> rows; int i=-1; while((i=ListView_GetNextItem(ui_.list,i,LVNI_SELECTED))!=-1) rows.push_back(i); return rows; }
void App::StartDownload(bool single,int row){ if(worker_.IsRunning()) return; if(!single){ queue_=SelectedRows(); queuePos_=0; sumDone_=0; sumTotal_=0; if(queue_.empty()) return; AppendLogText(BuildLogLine(L"总共选择 "+std::to_wstring(queue_.size())+L" 个文件")); for(int r:queue_) SetStatus(r,L"排队中"); row=queue_[0];}
    else if(queue_.empty()){ queue_={row}; queuePos_=0; sumDone_=0; sumTotal_=0; }
    wchar_t dir[1024]{}; GetWindowTextW(ui_.downloadDirEdit,dir,1024); if(wcslen(dir)==0){AppendLogText(BuildLogLine(L"下载目录为空")); return;} downloadDir_=dir;
    bool cancelAll=false, skip=false; std::wstring save=downloadDir_+L"\\"+items_[row].filename; if(!ConfirmOverwrite(save,cancelAll,skip)){ if(cancelAll){SetUiBusy(false); return;} if(skip){ SetStatus(row,L"已取消"); queuePos_++; if(queuePos_<(int)queue_.size()) StartDownload(true,queue_[queuePos_]); return; } }
    SetUiBusy(true); SetStatus(row,L"等待下载"); AppendLogText(BuildLogLine(L"正在下载第 "+std::to_wstring(queuePos_+1)+L" / "+std::to_wstring(queue_.size())+L" 个")); worker_.Start(hwnd_,row,queuePos_+1,(int)queue_.size(),items_[row].filename,items_[row].url,save,options_,WM_APP_PROGRESS,WM_APP_LOG,WM_APP_DONE);
}
void App::Cancel(){ cancelling_=true; worker_.Cancel(); }
void App::OpenDownloads(){ ShellExecuteW(hwnd_,L"open",downloadDir_.c_str(),nullptr,nullptr,SW_SHOW); }
void App::SetUiBusy(bool b){ EnableWindow(ui_.loadBtn,!b); EnableWindow(ui_.downloadBtn,!b); EnableWindow(ui_.cancelBtn,b); }
void App::DownloadAll(){ if(worker_.IsRunning()) return; queue_.clear(); for(int i=0;i<(int)items_.size();++i) queue_.push_back(i); if(queue_.empty()) return; queuePos_=0; sumDone_=0; sumTotal_=0; for(auto &it:items_) if(it.sizeKnown) sumTotal_+=it.sizeBytes; for(int r:queue_) SetStatus(r,L"等待"); StartDownload(true,queue_[0]); }
void App::LoadConfig(){ downloadDir_=ExeDir()+L"\\downloads"; auto ini=IniPath(); if(!std::filesystem::exists(ini)){ WritePrivateProfileStringW(L"General",L"DownloadDir",downloadDir_.c_str(),ini.c_str()); WritePrivateProfileStringW(L"Download",L"RetryCount",L"3",ini.c_str()); WritePrivateProfileStringW(L"Download",L"ConnectTimeoutMs",L"10000",ini.c_str()); WritePrivateProfileStringW(L"Download",L"SendTimeoutMs",L"30000",ini.c_str()); WritePrivateProfileStringW(L"Download",L"ReceiveTimeoutMs",L"30000",ini.c_str()); WritePrivateProfileStringW(L"Download",L"EnableResume",L"1",ini.c_str()); }
wchar_t buf[1024]{}; GetPrivateProfileStringW(L"General",L"DownloadDir",downloadDir_.c_str(),buf,1024,ini.c_str()); downloadDir_=buf; options_.retryCount=GetPrivateProfileIntW(L"Download",L"RetryCount",3,ini.c_str()); options_.connectTimeoutMs=GetPrivateProfileIntW(L"Download",L"ConnectTimeoutMs",10000,ini.c_str()); options_.dnsTimeoutMs=10000; options_.sendTimeoutMs=GetPrivateProfileIntW(L"Download",L"SendTimeoutMs",30000,ini.c_str()); options_.receiveTimeoutMs=GetPrivateProfileIntW(L"Download",L"ReceiveTimeoutMs",30000,ini.c_str()); options_.enableResume=GetPrivateProfileIntW(L"Download",L"EnableResume",1,ini.c_str())!=0; }
void App::SaveConfig(){ WritePrivateProfileStringW(L"General",L"DownloadDir",downloadDir_.c_str(),IniPath().c_str()); }
bool App::ChooseDownloadDir(){ BROWSEINFOW bi{}; bi.hwndOwner=hwnd_; bi.lpszTitle=L"选择下载目录"; PIDLIST_ABSOLUTE id=SHBrowseForFolderW(&bi); if(!id) return false; wchar_t p[MAX_PATH]{}; SHGetPathFromIDListW(id,p); CoTaskMemFree(id); downloadDir_=p; SetWindowTextW(ui_.downloadDirEdit,p); SaveConfig(); return true; }
void App::ClearStatuses(){ for(size_t i=0;i<items_.size();++i) SetStatus((int)i,L"等待"); }
void App::CopySelectedUrls(){ auto rows=SelectedRows(); std::wstring t; for(int r:rows) t += items_[r].url + L"\r\n"; if(OpenClipboard(hwnd_)){ EmptyClipboard(); size_t sz=(t.size()+1)*sizeof(wchar_t); HGLOBAL h=GlobalAlloc(GMEM_MOVEABLE,sz); memcpy(GlobalLock(h),t.c_str(),sz); GlobalUnlock(h); SetClipboardData(CF_UNICODETEXT,h); CloseClipboard(); }}
bool App::SaveLogs(){ SYSTEMTIME st{}; GetLocalTime(&st); wchar_t fn[128]; wsprintfW(fn,L"version-downloader-%04d%02d%02d-%02d%02d%02d.log",st.wYear,st.wMonth,st.wDay,st.wHour,st.wMinute,st.wSecond); std::wstring path=downloadDir_+L"\\"+fn; int len=GetWindowTextLengthW(ui_.logEdit); std::wstring txt(static_cast<size_t>(len)+1,L'\0'); GetWindowTextW(ui_.logEdit,txt.data(),len+1); txt.resize(static_cast<size_t>(len)); std::string utf8 = WideToUtf8(txt); HANDLE h = CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr); if(h==INVALID_HANDLE_VALUE){ return false; } DWORD written=0; const unsigned char bom[3]={0xEF,0xBB,0xBF}; WriteFile(h,bom,3,&written,nullptr); if(!utf8.empty()){ WriteFile(h,utf8.data(),(DWORD)utf8.size(),&written,nullptr);} CloseHandle(h); return true; }
bool App::ConfirmOverwrite(const std::wstring& path, bool& cancelAll, bool& skip){ cancelAll=false; skip=false; if(!std::filesystem::exists(path)) return true; int r=MessageBoxW(hwnd_,(L"文件已存在:\n"+path+L"\n是=覆盖, 否=跳过, 取消=取消全部").c_str(),L"文件已存在",MB_YESNOCANCEL|MB_ICONQUESTION); if(r==IDYES) return true; if(r==IDNO){skip=true; return false;} cancelAll=true; return false; }
